### ISSUE TITLE
Name merging

### ISSUE THREAD

**Issue by bomeara** [pablobarbera/scholarnetwork#1]
This is a beautiful package: thanks for making it. One issue I have with my network is names not merging: I'm Brian O'Meara, and my name appears in my network (user id vpjEkQwAAAAJ) as separate nodes for BC O'Meara (twice), BC O'MEARA, B O'Meara (twice), and BC O'meara. I see a few other nodes where they're not merged. Perhaps merge based on first initial, last name, ignoring case?

**Comment by pablobarbera** [comment]
Thanks a lot for the suggestion! This took a looong time, but a fix along these lines is now on the GitHub version of the package (and hopefully soon on CRAN as well).

**Comment by bomeara** [comment]
Thank you!
